/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './pages/__root'
import { Route as AppImport } from './pages/_app'
import { Route as AppUsertableImport } from './pages/_app/usertable'
import { Route as AppAudioplayerImport } from './pages/_app/audioplayer'

// Create Virtual Routes

const SigninLazyImport = createFileRoute('/signin')()
const AppIndexLazyImport = createFileRoute('/_app/')()

// Create/Update Routes

const SigninLazyRoute = SigninLazyImport.update({
  path: '/signin',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./pages/signin.lazy').then((d) => d.Route))

const AppRoute = AppImport.update({
  id: '/_app',
  getParentRoute: () => rootRoute,
} as any)

const AppIndexLazyRoute = AppIndexLazyImport.update({
  path: '/',
  getParentRoute: () => AppRoute,
} as any).lazy(() => import('./pages/_app/index.lazy').then((d) => d.Route))

const AppUsertableRoute = AppUsertableImport.update({
  path: '/usertable',
  getParentRoute: () => AppRoute,
} as any)

const AppAudioplayerRoute = AppAudioplayerImport.update({
  path: '/audioplayer',
  getParentRoute: () => AppRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppImport
      parentRoute: typeof rootRoute
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninLazyImport
      parentRoute: typeof rootRoute
    }
    '/_app/audioplayer': {
      id: '/_app/audioplayer'
      path: '/audioplayer'
      fullPath: '/audioplayer'
      preLoaderRoute: typeof AppAudioplayerImport
      parentRoute: typeof AppImport
    }
    '/_app/usertable': {
      id: '/_app/usertable'
      path: '/usertable'
      fullPath: '/usertable'
      preLoaderRoute: typeof AppUsertableImport
      parentRoute: typeof AppImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexLazyImport
      parentRoute: typeof AppImport
    }
  }
}

// Create and export the route tree

interface AppRouteChildren {
  AppAudioplayerRoute: typeof AppAudioplayerRoute
  AppUsertableRoute: typeof AppUsertableRoute
  AppIndexLazyRoute: typeof AppIndexLazyRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAudioplayerRoute: AppAudioplayerRoute,
  AppUsertableRoute: AppUsertableRoute,
  AppIndexLazyRoute: AppIndexLazyRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof AppRouteWithChildren
  '/signin': typeof SigninLazyRoute
  '/audioplayer': typeof AppAudioplayerRoute
  '/usertable': typeof AppUsertableRoute
  '/': typeof AppIndexLazyRoute
}

export interface FileRoutesByTo {
  '/signin': typeof SigninLazyRoute
  '/audioplayer': typeof AppAudioplayerRoute
  '/usertable': typeof AppUsertableRoute
  '/': typeof AppIndexLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_app': typeof AppRouteWithChildren
  '/signin': typeof SigninLazyRoute
  '/_app/audioplayer': typeof AppAudioplayerRoute
  '/_app/usertable': typeof AppUsertableRoute
  '/_app/': typeof AppIndexLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '' | '/signin' | '/audioplayer' | '/usertable' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/signin' | '/audioplayer' | '/usertable' | '/'
  id:
    | '__root__'
    | '/_app'
    | '/signin'
    | '/_app/audioplayer'
    | '/_app/usertable'
    | '/_app/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  SigninLazyRoute: typeof SigninLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  SigninLazyRoute: SigninLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_app",
        "/signin"
      ]
    },
    "/_app": {
      "filePath": "_app.tsx",
      "children": [
        "/_app/audioplayer",
        "/_app/usertable",
        "/_app/"
      ]
    },
    "/signin": {
      "filePath": "signin.lazy.tsx"
    },
    "/_app/audioplayer": {
      "filePath": "_app/audioplayer.tsx",
      "parent": "/_app"
    },
    "/_app/usertable": {
      "filePath": "_app/usertable.tsx",
      "parent": "/_app"
    },
    "/_app/": {
      "filePath": "_app/index.lazy.tsx",
      "parent": "/_app"
    }
  }
}
ROUTE_MANIFEST_END */
